import React,{useMemo,useState}from"react";
const MACHINE_NAME="TB290";
const SHEET_WEBAPP_URL=import.meta.env.VITE_GOOGLE_SCRIPT_URL||"";
function parseDecimal(v){if(v===null||v===undefined)return NaN;const c=String(v).trim().replace(/\s/g,"").replace(",",".");return c===""?NaN:Number(c)}
function formatHours(v){if(v===""||Number.isNaN(v))return"—";return v.toLocaleString("de-AT",{minimumFractionDigits:1,maximumFractionDigits:2})+" h"}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
export default function App(){const today=new Date().toISOString().slice(0,10);const[form,setForm]=useState({datumVon:today,datumBis:today,name:"",stundenStart:"",stundenEnde:"",diesel:"",einsatzart:"innerbetrieblich",bemerkung:"",getankt:false});const[message,setMessage]=useState("");const[sending,setSending]=useState(false);const[loadingLast,setLoadingLast]=useState(false);const startNumber=parseDecimal(form.stundenStart),endNumber=parseDecimal(form.stundenEnde),dieselNumber=parseDecimal(form.diesel);const gefahreneStunden=useMemo(()=>{const s=parseDecimal(form.stundenStart),e=parseDecimal(form.stundenEnde);if(Number.isNaN(s)||Number.isNaN(e))return"";return Math.round((e-s)*100)/100},[form.stundenStart,form.stundenEnde]);const hasValidHours=gefahreneStunden!==""&&gefahreneStunden>=0;const canSave=form.datumVon&&form.datumBis&&form.name.trim()&&!Number.isNaN(startNumber)&&!Number.isNaN(endNumber)&&hasValidHours&&form.getankt&&!sending;
async function takeLastValue(){setMessage("");if(!SHEET_WEBAPP_URL){setMessage("Google-Script-Link fehlt noch.");return}setLoadingLast(true);try{const r=await fetch(`${SHEET_WEBAPP_URL}?action=last&ts=${Date.now()}`);const d=await r.json();if(!d.ok||d.lastEnde===""||d.lastEnde==null){setMessage("Es wurde noch kein letzter Stundenzähler gefunden.");return}const last=String(d.lastEnde).replace(".",",");setForm(c=>({...c,stundenStart:last}));setMessage(`Letzter Stundenzähler übernommen: ${last}`)}catch{setMessage("Letzter Wert konnte nicht geladen werden. Bitte Google-Script prüfen.")}finally{setLoadingLast(false)}}
async function saveEntry(e){e.preventDefault();setMessage("");if(!SHEET_WEBAPP_URL){setMessage("Google-Script-Link fehlt noch.");return}if(!canSave){alert("Bitte alle Pflichtfelder ausfüllen und 'Getankt' anhaken.");return}setSending(true);const payload={maschine:MACHINE_NAME,datumVon:form.datumVon,datumBis:form.datumBis,name:form.name.trim(),stundenStart:startNumber,stundenEnde:endNumber,betriebsstunden:Number(gefahreneStunden),diesel:Number.isNaN(dieselNumber)?0:dieselNumber,einsatzart:form.einsatzart,getankt:form.getankt,bemerkung:form.bemerkung.trim(),erfasstAm:new Date().toISOString()};try{await fetch(SHEET_WEBAPP_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});setMessage("Eintrag wurde gespeichert.");setForm({datumVon:today,datumBis:today,name:"",stundenStart:"",stundenEnde:"",diesel:"",einsatzart:"innerbetrieblich",bemerkung:"",getankt:false})}catch{setMessage("Speichern fehlgeschlagen. Bitte Internetverbindung prüfen.")}finally{setSending(false)}}
return <div className="page"><main className="app-card"><header className="top"><div className="logo"><img src="/logo.png" alt="Takeuchi TB290" /></div><div style={{marginLeft:"15px"}}>
  <h1>{MACHINE_NAME}</h1>
  <p>Stundenerfassung</p>
</div></div></header>{message&&<div className="message">{message}</div>}<form onSubmit={saveEntry} className="form"><section className="section"><h2>Zeitraum</h2><div className="grid two"><Field label="Von"><input type="date" value={form.datumVon} onChange={e=>setForm({...form,datumVon:e.target.value})}/></Field><Field label="Bis"><input type="date" value={form.datumBis} onChange={e=>setForm({...form,datumBis:e.target.value})}/></Field></div></section><section className="section"><h2>Einsatz</h2><Field label="Name / Fahrer"><input type="text" placeholder="Name eingeben" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Einsatzart"><select value={form.einsatzart} onChange={e=>setForm({...form,einsatzart:e.target.value})}><option value="innerbetrieblich">Innerbetrieblich</option><option value="ueberbetrieblich">Überbetrieblich</option></select></Field></section><section className="section"><h2>Betriebsstunden</h2><button type="button" className="secondary" onClick={takeLastValue} disabled={loadingLast}>{loadingLast?"Lade letzten Wert...":"Letzten Wert übernehmen"}</button><div className="grid two"><Field label="Stundenzähler Beginn"><input type="text" inputMode="decimal" placeholder="z. B. 1250,5" value={form.stundenStart} onChange={e=>setForm({...form,stundenStart:e.target.value})}/></Field><Field label="Stundenzähler Ende"><input type="text" inputMode="decimal" placeholder="z. B. 1253,0" value={form.stundenEnde} onChange={e=>setForm({...form,stundenEnde:e.target.value})}/></Field></div><div className={!hasValidHours&&form.stundenStart&&form.stundenEnde?"result error":"result"}><span>Gefahrene Stunden</span><strong>{formatHours(gefahreneStunden)}</strong></div></section><section className="section"><h2>Kontrolle</h2><Field label="Getankte Dieselmenge in Liter"><input type="text" inputMode="decimal" placeholder="z. B. 18,5" value={form.diesel} onChange={e=>setForm({...form,diesel:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={form.getankt} onChange={e=>setForm({...form,getankt:e.target.checked})}/><span>Getankt</span></label></section><section className="section"><Field label="Bemerkung / Schäden"><textarea placeholder="z. B. Schaden, Wartung, Besonderheiten" value={form.bemerkung} onChange={e=>setForm({...form,bemerkung:e.target.value})}/></Field></section><button className="primary" type="submit" disabled={!canSave}>{sending?"Speichert...":"Eintrag speichern"}</button></form><footer>© by Steininger Flo</footer></main></div>}
